module.exports = {
	defaults: {
		provider: "unsplash",
		order: "latest",
		posts_per_page: "&per_page=20",
	},
	unsplash: {
		requires_key: false,
		new: false,
		filters: true,
		api_query_var: "/?client_id=",
		photo_api: "https://api.unsplash.com/photos",
		collections_api: "https://api.unsplash.com/collections",
		search_api: "https://api.unsplash.com/search/photos",
		search_query_var: "query",
		arr_key: "results",
		orientation: ["landscape", "portrait", "squarish"],
	},
	pixabay: {
		requires_key: true,
		new: false,
		filters: true,
		api_query_var: "/?key=",
		photo_api: "https://pixabay.com/api",
		search_api: "https://pixabay.com/api",
		search_query_var: "q",
		arr_key: "hits",
		orientation: ["horizontal", "vertical"],
	},
};
