module.exports = {
	unsplash: {
		requires_key: false,
		app_id: instant_img_localize.unsplash_app_id,
		api_query_var: "/?client_id=",
		photo_api: "https://api.unsplash.com/photos",
		collections_api: "https://api.unsplash.com/collections",
		search_api: "https://api.unsplash.com/search/photos",
		search_query_var: "query",
		arr_key: "results",
		order_key: "order_by",
		order: ["latest", "popular", "oldest"],
		orientation: ["landscape", "portrait", "squarish"],
	},
	pixabay: {
		requires_key: true,
		//app_id: "",
		//app_id: "23559219-67621b8a8bd93df7b6aef72a7",
		app_id: instant_img_localize.pixabay_app_id,
		api_query_var: "/?key=",
		photo_api: "https://pixabay.com/api",
		search_api: "https://pixabay.com/api",
		search_query_var: "q",
		arr_key: "hits",
		order_key: "order",
		order: ["latest", "popular"],
		orientation: ["horizontal", "vertical"],
	},
	posts_per_page: "&per_page=20",
};
