module.exports = {
	unsplash: {
		filters: {
			order_by: {
				label: "orderby",
				filters: ["latest", "oldest", "popular"],
			},
		},
		search: {
			order_by: {
				label: "orderby",
				filters: ["relevance", "latest"],
			},
			orientation: {
				label: "orientation",
				option: "select",
				filters: ["landscape", "portrait", "squarish"],
			},
			color: {
				label: "colors",
				option: "select",
				filters: [
					"black_and_white",
					"black",
					"white",
					"yellow",
					"orange",
					"red",
					"purple",
					"magenta",
					"green",
					"teal",
					"blue",
				],
			},
		},
	},
	pixabay: {
		filters: {
			order: {
				label: "orderby",
				filters: ["latest", "popular"],
			},
			image_type: {
				label: "type",
				filters: ["all", "photo", "illustration", "vector"],
			},
			category: {
				label: "category",
				option: "select",
				filters: [
					"backgrounds",
					"fashion",
					"nature",
					"science",
					"education",
					"feelings",
					"health",
					"people",
					"religion",
					"places",
					"animals",
					"industry",
					"computer",
					"food",
					"sports",
					"transportation",
					"travel",
					"buildings",
					"business",
					"music",
				],
			},
			colors: {
				label: "colors",
				option: "select",
				filters: [
					"grayscale",
					"transparent",
					"red",
					"orange",
					"yellow",
					"green",
					"turquoise",
					"blue",
					"lilac",
					"pink",
					"white",
					"gray",
					"black",
					"brown",
				],
			},
			orientation: {
				label: "orientation",
				filters: ["all", "horizontal", "vertical"],
			},
		},
	},
};
