module.exports = {
	unsplash: {
		order: {
			label: "orderby",
			filters: ["latest", "oldest", "popular"],
		},
	},
	pixabay: {
		order: {
			label: "orderby",
			filters: ["latest", "popular"],
		},
		image_type: {
			label: "type",
			filters: ["all", "photo", "illustration", "vector"],
		},
		category: {
			label: "category",
			option: "select",
			filters: [
				"backgrounds",
				"fashion",
				"nature",
				"science",
				"education",
				"feelings",
				"health",
				"people",
				"religion",
				"places",
				"animals",
				"industry",
				"computer",
				"food",
				"sports",
				"transportation",
				"travel",
				"buildings",
				"business",
				"music",
			],
		},
		colors: {
			label: "colors",
			option: "select",
			filters: [
				"grayscale",
				"transparent",
				"red",
				"orange",
				"yellow",
				"green",
				"turquoise",
				"blue",
				"lilac",
				"pink",
				"white",
				"gray",
				"black",
				"brown",
			],
		},
		orientation: {
			label: "orientation",
			filters: ["all", "horizontal", "vertical"],
		},
	},
};
